package com.blewifi.presence

import org.junit.Assert.assertEquals
import org.junit.Test

/** Vectors generated by backend/app/tokens.py token_for(); the Kotlin code must match them. */
class TokenTest {
    private val s1 = "000102030405060708090a0b0c0d0e0f"
    private val s2 = "ffeeddccbbaa99887766554433221100"

    @Test fun windowZero() = assertEquals("20fa59fd604ac7f7", Token.forWindow(s1, 0))

    @Test fun largeWindow() = assertEquals("54aefc6c2b2def1b", Token.forWindow(s1, 57000000))

    @Test fun negativeWindow() = assertEquals("a63aa970d7fce9d4", Token.forWindow(s2, -1))

    @Test fun windowRollsEvery30s() {
        assertEquals(0L, Token.window(29))
        assertEquals(1L, Token.window(30))
    }
}
