"""Train the Wi-Fi RSSI fingerprint -> zone KNN classifier (brief section 36)
on synthetic campus data, evaluate it on a held-out split, and save
models/wifi_localization.joblib.

    python train_wifi_model.py

Accuracy numbers come from SYNTHETIC fingerprints generated by an actual RF
propagation model (simulator/campus.py: free-space path loss + multi-wall
attenuation), not real phone scans -- reported here as a "synthetic
benchmark" and never presented as a measurement of real-world accuracy
(brief section 37's own instruction: "do not manufacture good metrics").
"""
from __future__ import annotations

import argparse

import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

from app.wifi_knn import WifiFingerprintModel
from simulator.campus import build_campus, wifi_training_pairs


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--classrooms", type=int, default=20)
    ap.add_argument("--aps", type=int, default=10)
    ap.add_argument("--samples-per-room", type=int, default=60)
    ap.add_argument("--neighbors", type=int, default=5)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", default="models/wifi_localization.joblib")
    args = ap.parse_args(argv)

    rng = np.random.default_rng(args.seed)
    classrooms, aps, _ = build_campus(args.classrooms, args.aps)
    fingerprints, zones = wifi_training_pairs(classrooms, aps, rng, args.samples_per_room)

    idx = np.arange(len(fingerprints))
    train_idx, test_idx = train_test_split(idx, test_size=0.25, stratify=zones, random_state=args.seed)
    fps_train = [fingerprints[i] for i in train_idx]
    zones_train = [zones[i] for i in train_idx]
    fps_test = [fingerprints[i] for i in test_idx]
    zones_test = [zones[i] for i in test_idx]

    model = WifiFingerprintModel(n_neighbors=args.neighbors).fit(fps_train, zones_train)
    preds = [model.predict(fp).zone for fp in fps_test]
    acc = accuracy_score(zones_test, preds)
    cm = confusion_matrix(zones_test, preds, labels=sorted({z for z in zones}))

    print("=== SYNTHETIC BENCHMARK -- not a real-world accuracy measurement ===")
    print(f"{len(classrooms)} classrooms, {len(aps)} APs, {len(fingerprints)} fingerprints "
          f"({len(fps_train)} train / {len(fps_test)} test, {args.neighbors}-NN)")
    print(f"zone accuracy: {acc:.3f}")
    print(f"confusion matrix shape: {cm.shape} (rows=true zone, cols=predicted zone)")
    off_diagonal = cm.sum() - np.trace(cm)
    print(f"total misclassifications: {off_diagonal} of {cm.sum()}")

    model.save(args.out)
    print(f"\nsaved {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
